/*
    Almar Dave Ramos, Brix Centeno
    
 */
package Main.User;

import Client.Books.BooksProperties;
import Main.Generator;
import Main.Loader;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlmarDave
 */
public class Dashboard extends JFrame {

    String AccountID;
    BooksProperties bp = new BooksProperties();
    /**
     * Creates new form NewJFrame
     */
     int x, y;
     Loader l = new Loader();

    /**
     *
     * @param AccountID
     */
    public Dashboard(String AccountID) {
        initComponents();
        this.AccountID = AccountID;
        startup(AccountID);
        lblTop.setText("Library Management System");
    }
    void startup(String AccountID)
    {
        setLocationRelativeTo(null);
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=DB_LMS;integratedSecurity=true","DESKTOP-T51D5JD\\AlmarDave","");
            PreparedStatement s = con.prepareStatement("Select FName, LName FROM ACCOUNT WHERE AccID = ?");
            s.setString(1,AccountID);
            ResultSet rs = s.executeQuery();
            if (rs.next()) {
                lblFName.setText(rs.getString("FName"));
                lblLName.setText(rs.getString("LName"));
            }
            lblAvailBook.setText(String.valueOf(l.getBookCount()));
            lblBookBorrowed.setText(l.getBookCount(AccountID));
            lblBookPos.setText(l.getPendingBookCount(AccountID));
            tblAllBooks.setModel(l.getTableContentModel("BOOK"));
            tblHorror.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Horror"));
            tblNovel.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Novel"));
            tblSciFi.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "sci-fi"));
            tblBiog.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Biography"));
            tblBiog.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Biography"));
            tblHistory.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "History"));
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Server Error \n ERROR: " + ex.getErrorCode() +"\n"+ex,"Connection Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        lblTop = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        MainTab = new javax.swing.JTabbedPane();
        pnlNovel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNovel = new javax.swing.JTable();
        pnlHistory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        pnlHorror = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHorror = new javax.swing.JTable();
        pnlBio = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBiog = new javax.swing.JTable();
        pnlSciFi = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSciFi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAllBooks = new javax.swing.JTable();
        btnCustomProf = new javax.swing.JButton();
        lblUserPic = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblTotBook = new javax.swing.JLabel();
        lblBookBor = new javax.swing.JLabel();
        lblPend = new javax.swing.JLabel();
        lblBookBorrowed = new javax.swing.JLabel();
        lblAvailBook = new javax.swing.JLabel();
        lblBookPos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1060, 700));

        lblTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTopMouseDragged(evt);
            }
        });
        lblTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTopMousePressed(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setToolTipText("Close");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setText("_");
        lblMin.setToolTipText("Minimize");
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });

        lblLogo.setText("LOGO");

        MainTab.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        tblNovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblNovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNovelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNovel);

        javax.swing.GroupLayout pnlNovelLayout = new javax.swing.GroupLayout(pnlNovel);
        pnlNovel.setLayout(pnlNovelLayout);
        pnlNovelLayout.setHorizontalGroup(
            pnlNovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        pnlNovelLayout.setVerticalGroup(
            pnlNovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        MainTab.addTab("Novel", null, pnlNovel, "Books of Novel");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHistory);

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        MainTab.addTab("History", null, pnlHistory, "Books of History");

        tblHorror.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHorror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHorrorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHorror);

        javax.swing.GroupLayout pnlHorrorLayout = new javax.swing.GroupLayout(pnlHorror);
        pnlHorror.setLayout(pnlHorrorLayout);
        pnlHorrorLayout.setHorizontalGroup(
            pnlHorrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        pnlHorrorLayout.setVerticalGroup(
            pnlHorrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        MainTab.addTab("Horror", null, pnlHorror, "Books of Horror");

        tblBiog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblBiog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBiogMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBiog);

        javax.swing.GroupLayout pnlBioLayout = new javax.swing.GroupLayout(pnlBio);
        pnlBio.setLayout(pnlBioLayout);
        pnlBioLayout.setHorizontalGroup(
            pnlBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        pnlBioLayout.setVerticalGroup(
            pnlBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        MainTab.addTab("Biography", null, pnlBio, "Books of Biography");

        tblSciFi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSciFi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSciFiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblSciFiMouseEntered(evt);
            }
        });
        jScrollPane5.setViewportView(tblSciFi);

        javax.swing.GroupLayout pnlSciFiLayout = new javax.swing.GroupLayout(pnlSciFi);
        pnlSciFi.setLayout(pnlSciFiLayout);
        pnlSciFiLayout.setHorizontalGroup(
            pnlSciFiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        pnlSciFiLayout.setVerticalGroup(
            pnlSciFiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        MainTab.addTab("Sci-Fi", null, pnlSciFi, "Books of Sci-Fi");

        tblAllBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAllBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllBooksMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblAllBooks);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        MainTab.addTab("All Books", jPanel1);

        MainTab.setSelectedIndex(5);

        btnCustomProf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCustomProf.setText("Customize Profile");

        lblUserPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserPic.setText("User's Pic");
        lblUserPic.setToolTipText("Your Picture");
        lblUserPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblLName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLName.setText("Your Last Name");

        lblFName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblFName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFName.setText("Your First Name");

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSearch.setText("Search Book");

        lblTotBook.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTotBook.setText("Available to Borrow");
        lblTotBook.setToolTipText("");

        lblBookBor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBookBor.setText("Books Borrowed");
        lblBookBor.setToolTipText("");

        lblPend.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPend.setText("Pending to return");
        lblPend.setToolTipText("");

        lblBookBorrowed.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBookBorrowed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookBorrowed.setText("ATR Borrowed");
        lblBookBorrowed.setToolTipText("Books You've borrowed and returned");

        lblAvailBook.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblAvailBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailBook.setText("Books in Library");
        lblAvailBook.setToolTipText("Books that can be Found in the Library");

        lblBookPos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBookPos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPos.setText("Books in possession");
        lblBookPos.setToolTipText("Books that you haven't returned yet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomProf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSearch)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTotBook)
                                .addGap(72, 72, 72)
                                .addComponent(lblPend)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAvailBook, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBookPos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookBor)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBookBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTop, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserPic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBookBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvailBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBookPos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotBook)
                            .addComponent(lblBookBor)
                            .addComponent(lblPend))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLName, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(btnCustomProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTopMouseDragged
        // TODO add your handling code here:
        //sets the location of the frame using the formula of (XframeLoc - mouseX, YFrameLoc - mouseY)
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
        
        //check if the frame is visible or active
        if (bp != null || (bp.getParent() != null&&bp.isActive())) {
            bp.setLocation(this.getX() + 1070, this.getY());
        }
    }//GEN-LAST:event_lblTopMouseDragged

    private void lblTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTopMousePressed
        // TODO add your handling code here:
        //get's the mouse current location
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblTopMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        lblClose.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setForeground(lblLogo.getForeground());
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        // when the mouse entered, the font color or the foreground 
        lblMin.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        //restores the font color from the original
        lblMin.setForeground(lblLogo.getForeground());
    }//GEN-LAST:event_lblMinMouseExited

    private void tblNovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNovelMouseClicked
        /*
        * when a row is selected, the properties pops up and pass the arguement and load the properties
        * create a function to retrieve book name, publisher, and author
        */
        bp = new BooksProperties(tblNovel.getValueAt(tblNovel.getSelectedRow(), tblNovel.getSelectedColumn()).toString(),AccountID);
        bp.setVisible(true);
        bp.setLocation(this.getY() + 1070, this.getX());
    }//GEN-LAST:event_tblNovelMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        int tab = MainTab.getSelectedIndex();
        switch (tab) {
            case 0:
            tblNovel.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Novel' and BookTitle like '%"+txtSearch.getText()+"%"));
                break;
            case 1:
            tblHistory.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "History' and BookTitle like '%"+txtSearch.getText()+"%"));
                break;
            case 2:
            tblHorror.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Horror' and BookTitle like '%"+txtSearch.getText()+"%"));
                break;
            case 3:
            tblBiog.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "Biography' and BookTitle like '%"+txtSearch.getText()+"%"));
                break;
            case 4:
            tblSciFi.setModel(l.getTableContentModel(new DefaultTableModel(),"Book", "sci-fi' and BookTitle like '%"+txtSearch.getText()+"%"));
                break;
            case 5:
                tblAllBooks.setModel(l.getTableContentModel(new DefaultTableModel(),"Book","' and BookTitle like '%"+txtSearch.getText()+"%"));
                break;
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoryMouseClicked
        /*
        * when a row is selected, the properties pops up and pass the arguement and load the properties
        * create a function to retrieve book name, publisher, and author
        */
        bp.setVisible(false);
        System.out.println(tblHistory.getValueAt(tblHistory.getSelectedRow(), 0));
        bp = new BooksProperties(tblHistory.getValueAt(tblHistory.getSelectedRow(), 0).toString(),AccountID);
        bp.setVisible(true);
        bp.setLocation(this.getY() + 1070, this.getX());
    }//GEN-LAST:event_tblHistoryMouseClicked

    private void tblHorrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHorrorMouseClicked
        /*
        * when a row is selected, the properties pops up and pass the arguement and load the properties
        * create a function to retrieve book name, publisher, and author
        */
        bp.setVisible(false);
        bp = new BooksProperties(tblHorror.getValueAt(tblHorror.getSelectedRow(), 0).toString(),AccountID);
        bp.setVisible(true);
        bp.setLocation(this.getY() + 1070, this.getX());
    }//GEN-LAST:event_tblHorrorMouseClicked

    private void tblBiogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBiogMouseClicked
        /*
        * when a row is selected, the properties pops up and pass the arguement and load the properties
        * create a function to retrieve book name, publisher, and author
        */
        bp.setVisible(false);
        bp = new BooksProperties(tblBiog.getValueAt(tblBiog.getSelectedRow(), 0).toString(),AccountID);
        bp.setVisible(true);
        bp.setLocation(this.getY() + 1070, this.getX());
    }//GEN-LAST:event_tblBiogMouseClicked

    private void tblSciFiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSciFiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSciFiMouseEntered

    private void tblSciFiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSciFiMouseClicked
        /*
        * when a row is selected, the properties pops up and pass the arguement and load the properties
        * create a function to retrieve book name, publisher, and author
        */
        bp.setVisible(false);
        bp = new BooksProperties(tblSciFi.getValueAt(tblSciFi.getSelectedRow(), 0).toString(),AccountID);
        bp.setVisible(true);
        bp.setLocation(this.getY() + 1070, this.getX());
    }//GEN-LAST:event_tblSciFiMouseClicked

    private void tblAllBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllBooksMouseClicked
        /*
        * when a row is selected, the properties pops up and pass the arguement and load the properties
        * create a function to retrieve book name, publisher, and author
        */
        bp.setVisible(false);
        bp = new BooksProperties(tblAllBooks.getValueAt(tblAllBooks.getSelectedRow(), 0).toString(),AccountID);
        bp.setVisible(true);
        bp.setLocation(this.getY() + 1070, this.getX());
    }//GEN-LAST:event_tblAllBooksMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JButton btnCustomProf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAvailBook;
    private javax.swing.JLabel lblBookBor;
    private javax.swing.JLabel lblBookBorrowed;
    private javax.swing.JLabel lblBookPos;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblPend;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTop;
    private javax.swing.JLabel lblTotBook;
    private javax.swing.JLabel lblUserPic;
    private javax.swing.JPanel pnlBio;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlHorror;
    private javax.swing.JPanel pnlNovel;
    private javax.swing.JPanel pnlSciFi;
    private javax.swing.JTable tblAllBooks;
    private javax.swing.JTable tblBiog;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblHorror;
    private javax.swing.JTable tblNovel;
    private javax.swing.JTable tblSciFi;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
