/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author AlmarDave
 */
public class SignUp extends JFrame implements ActionListener {

    /**
     * Creates new form SignUp
     */
    char source;
    String manager,auth;
    int x, y,ctr;
    StartingPoint sp = new StartingPoint();
    Generator g = new Generator();
    public SignUp() {
        load();
    }
    
    public SignUp(String manager, String auth,String title) {
        load();
        lblTop.setText(title);
        this.manager = manager;
        this.auth = auth;
        source = 'd';
    }

    public SignUp(String manager, String auth) {
        load();
        this.manager = manager;
        this.auth = auth;
        source = 'l';
    }

    private void load()
    {
        initComponents();
        txtFName.requestFocus();
        btnConfirm.setEnabled(false);
        pbPassInteg.setMaximum(100);
        pbPassInteg.setMinimum(0);
        setLocationRelativeTo(null);
        btnConfirm.addActionListener(this);
        captcha();
    }
    void captcha()
    {
        int captcha = (int) (Math.random() * 99999);
        lblCaptcha.setText(String.valueOf(captcha));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblPassCon = new javax.swing.JLabel();
        lblBDate = new javax.swing.JLabel();
        txtBDate = new com.toedter.calendar.JDateChooser();
        lblLName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPWord = new javax.swing.JPasswordField();
        txtPwordCon = new javax.swing.JPasswordField();
        lblAdd = new javax.swing.JLabel();
        spAdd = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        chkTC = new javax.swing.JCheckBox();
        lblCaptcha = new javax.swing.JLabel();
        btnCaptcha = new javax.swing.JButton();
        lblTerms = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCondition = new javax.swing.JLabel();
        pbPassInteg = new javax.swing.JProgressBar();
        lblTop = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        txtUName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();

        setTitle("Sign Up");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(458, 702));

        lblFName.setText("First Name");

        lblEmail.setText("Email");

        lblPass.setText("Password");

        lblPassCon.setText("Confim Password");

        lblBDate.setText("Birth Date");

        txtBDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblLName.setText("Last Name");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        txtPWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPWordKeyReleased(evt);
            }
        });

        lblAdd.setText("Address");

        txtAdd.setColumns(20);
        txtAdd.setRows(5);
        spAdd.setViewportView(txtAdd);

        chkTC.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkTC.setText("I agree with");
        chkTC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTCStateChanged(evt);
            }
        });

        lblCaptcha.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        lblCaptcha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaptcha.setText("15487");

        btnCaptcha.setText("Captcha");
        btnCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptchaActionPerformed(evt);
            }
        });

        lblTerms.setText("Terms");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("and");

        lblCondition.setText("Conditions");

        pbPassInteg.setMaximumSize(new java.awt.Dimension(32767, 10));
        pbPassInteg.setMinimumSize(new java.awt.Dimension(10, 10));
        pbPassInteg.setPreferredSize(new java.awt.Dimension(146, 10));

        lblTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTopMouseDragged(evt);
            }
        });
        lblTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTopMousePressed(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setText("Your Picture");
        lblPic.setToolTipText("Click here to add a picture");
        lblPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPicMouseClicked(evt);
            }
        });

        txtCaptcha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Contact No");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Username");

        btnConfirm.setText("Confirm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFName)
                            .addComponent(lblLName)
                            .addComponent(txtFName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtLName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPass)))
                                        .addComponent(lblPassCon))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPwordCon, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPWord, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pbPassInteg, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUName)
                                        .addComponent(txtContactNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEmail)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblBDate)
                            .addGap(44, 44, 44)
                            .addComponent(txtBDate, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCaptcha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkTC)
                        .addGap(0, 0, 0)
                        .addComponent(lblTerms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCondition)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirm)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(pbPassInteg, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassCon)
                    .addComponent(txtPwordCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBDate)
                    .addComponent(txtBDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdd)
                    .addComponent(spAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCaptcha))
                    .addComponent(lblCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTC)
                    .addComponent(lblTerms)
                    .addComponent(jLabel1)
                    .addComponent(lblCondition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Top Navigation Bar Dragged">       
    private void lblTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTopMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_lblTopMouseDragged
    // </editor-fold>  
    
    
    // <editor-fold defaultstate="collapsed" desc="Top Navigation Bar Clicked"> 
    private void lblTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTopMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblTopMousePressed
    // </editor-fold>
    
    
    // <editor-fold defaultstate="collapsed" desc="Close Button Clicked"> 
    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        if (source == 'l') {
            int c = JOptionPane.showConfirmDialog(null, "Any changes wont be saved, are sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (c == 0) {
                this.setVisible(false);
                sp.setVisible(true);
            }
        }
    }//GEN-LAST:event_lblCloseMouseClicked
    // </editor-fold>
    
    
    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        lblClose.setForeground(Color.red);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setForeground(lblAdd.getForeground());
    }//GEN-LAST:event_lblCloseMouseExited

    private void btnCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptchaActionPerformed
        // TODO add your handling code here:
        int captcha = (int) (10000 + Math.random() * 99999);
        lblCaptcha.setText(String.valueOf(captcha));
    }//GEN-LAST:event_btnCaptchaActionPerformed

    private void chkTCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTCStateChanged
        // TODO add your handling code here:
        if (chkTC.isSelected()) {
            btnConfirm.setEnabled(true);
        }
        else
        {
            btnConfirm.setEnabled(false);
        }
    }//GEN-LAST:event_chkTCStateChanged

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void lblPicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPicMouseClicked

    }//GEN-LAST:event_lblPicMouseClicked

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtPWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPWordKeyReleased
        
    }//GEN-LAST:event_txtPWordKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaptcha;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JCheckBox chkTC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBDate;
    private javax.swing.JLabel lblCaptcha;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPassCon;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblTerms;
    private javax.swing.JLabel lblTop;
    private javax.swing.JProgressBar pbPassInteg;
    private javax.swing.JScrollPane spAdd;
    private javax.swing.JTextArea txtAdd;
    private com.toedter.calendar.JDateChooser txtBDate;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JPasswordField txtPWord;
    private javax.swing.JPasswordField txtPwordCon;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables

void resetFields()
{
    txtFName.setText("");
    txtLName.setText("");
    txtUName.setText("");
    txtPWord.setText("");
    txtPwordCon.setText("");
    txtEmail.setText("");
    txtAdd.setText("");
    txtContactNo.setText("");
    txtBDate.cleanup();
    txtCaptcha.setText("");
    chkTC.setSelected(false);
    btnConfirm.setEnabled(false);
    txtFName.requestFocus();
    captcha();
}

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == btnConfirm) {
            try {
                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=DB_LMS;integratedSecurity=true","DESKTOP-VTJ87TV\\AlmarDave","");
                PreparedStatement s = con.prepareStatement("insert into ACCOUNT values "
                        + "("+g.getAccountID()+"," //ACCID generator
                            + "null," //further analysis and 
                                + "'"+txtUName.getText()+"',"
                                        + "'"+txtPWord.getText()+"',"
                                                + "'"+txtFName.getText()+"',"
                                                        + "'"+txtLName.getText()+"',"
                                                                + "'"+txtAdd.getText()+"',"
                                                                        + "'"+txtEmail.getText()+"',"
                                                                                + ""+txtContactNo.getText()+","
                                                                                        + "'"+g.getActivationCode()+"',"
                                                                                                + "'"+auth+"',"
                                                                                                        + ""+manager+")");
                        /*
                *****************************
                *    Data Type Sequence     *
                *                           *
                *    AccID int 10 dgt       *
                *    AccPic BLOB            *
                *    USERNAME String        *
                *    PWord String           *
                *    FName String           *
                *    LName String           *
                *    AccAdd String          *
                *    Email String           *
                *    ContactNo int 11 dgt   *
                *    Status String          *
                *    AccAuth String         *
                *    Manager int 10 dgt     *
                *                           *
                *****************************
                */
                
                s.execute();
                System.out.println("command successful");
                resetFields();
                if (JOptionPane.showConfirmDialog(null, "Great! we've sent an \nactivation code to your e-mail!\nit will be activated on your first log in!\n Do you wish to log - in now?","Activation", JOptionPane.YES_NO_OPTION) == 0) {
                    this.setVisible(false);
                    LoginForm lf = new LoginForm();
                    lf.setVisible(true);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: "+ex.getErrorCode()+"\n"+ex.getLocalizedMessage(), "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
}

